#@host = http://81.68.125.115:5678
@host = http://localhost:5678

@cpath = ""

###scan
GET {{host}}{{cpath}}/scan

###login
POST {{host}}{{cpath}}/user/login

{"username":"admin","password":"111111"}

###resetPassword
POST {{host}}{{cpath}}/user/resetpass

{"oldpass":"111111","newpass":"111111"}

###register
POST {{host}}{{cpath}}/user/register

{"username":"admin","password":"111111"}

###userLike
GET {{host}}{{cpath}}/user/like?queryString=a


###upload
POST {{host}}{{cpath}}/file/upload?folderId=4 HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryL3uJ3c0mfMKL94BR

------WebKitFormBoundaryL3uJ3c0mfMKL94BR
Content-Disposition: form-data; name="file"; filename="test.png"
Content-Type: application/octet-stream

< test.png
------WebKitFormBoundaryL3uJ3c0mfMKL94BR--

###checkLibraryName false
GET {{host}}{{cpath}}/library/check?name=Default Library


###checkLibraryName true
GET {{host}}{{cpath}}/library/check?name=test
